### ISSUE TITLE
发生错误：'Event' object has no attribute 'prefix'

### ISSUE THREAD

**Issue by RyouSY** [Yuri-YuzuChaN/voice#1]
![Snipaste_2022-08-26_10-42-02](https://user-images.githubusercontent.com/42777611/186805197-49955400-e6de-465d-85ad-bf596897bc3e.png)

**Comment by Yuri-YuzuChaN** [comment]
把 nonebot 和 aiocqhttp 更新到最新版本

**Comment by RyouSY** [comment]
然后就出现新问题了
![Snipaste_2022-08-26_12-40-42](https://user-images.githubusercontent.com/42777611/186823501-6a4f39a2-6f91-4970-b66f-c572611039e8.png)

**Comment by Yuri-YuzuChaN** [comment]
这个大多是自己的网络问题

**Comment by RyouSY** [comment]
git pull之后错误变成list index out of range了
